[package]
name = "git-jmp"
version = "0.2.0"
edition = "2024"
description = "A fast, interactive Git branch switcher with fuzzy search and recency sorting"
license = "MIT"
repository = "https://github.com/pkitazos/git-jmp"
homepage = "https://github.com/pkitazos/git-jmp"
readme = "README.md"
keywords = ["git", "branch", "cli", "tui"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = { version = "4.6.5", features = ["unstable-dynamic"] }
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.30.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
toml = "1.1.2"
ureq = { version = "3", features = ["json"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
